### ISSUE TITLE
1.0.2 "make" error on Suse11

### ISSUE THREAD

**Issue by haih** [CUCmehp/occiwrapper#1]
"make" on  Suse11, show the error as follow:
Making all in .
make[1]: Entering directory `/home/haihu/occiwrapper/occiwrapper-1.0.2'
/bin/sh ./libtool --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPAC"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_AVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIMITS_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1E_R=1 -DHAVE_MEMMOVE=1 -I. -I. -I./include -I/home/haihu/occiwrapper/instantclient-sdk-linux/instantclient_12_1/sdk/include/ -std=gnu++0x   -gFactory.lo -MD -MP -MF .deps/SessionFactory.Tpo -c -o SessionFactory.lo SessionFactory.cpp
libtool: compile:  g++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DSTDCE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINTTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIMITS_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_LOCALTIME_R=1 -DHA -I. -I./include -I/home/haihu/occiwrapper/instantclient-sdk-linux/instantclient_12_1/sdk/include/ -std=gnu++0x -g -O2 -MT SessionFactory.lo -/SessionFactory.Tpo -c SessionFactory.cpp  -fPIC -DPIC -o .libs/SessionFactory.o
In file included from ./include/OcciWrapper/AbstractBinding.h:3,
                 from ./include/OcciWrapper/Binding.h:3,
                 from ./include/OcciWrapper/StatementImpl.h:9,
                 from ./include/OcciWrapper/Session.h:6,
                 from ./include/OcciWrapper/SessionFactory.h:4,
                 from SessionFactory.cpp:1:
./include/OcciWrapper/TypeHandler.h: In static member function ‘static void occiwrapper::TypeHandler<T>::extract(size_t, occiwrapper::Abstract
./include/OcciWrapper/TypeHandler.h:337: 错误：‘malloc’的实参不依赖模板参数，所以‘malloc’的声明必须可用
./include/OcciWrapper/TypeHandler.h:337: 错误：(如果您使用‘-fpermissive’，G++ 会接受您的代码，但是允许使用未定义的名称是不建议使用的风格)
./include/OcciWrapper/TypeHandler.h:339: 错误：‘malloc’的实参不依赖模板参数，所以‘malloc’的声明必须可用
./include/OcciWrapper/TypeHandler.h:341: 错误：‘malloc’的实参不依赖模板参数，所以‘malloc’的声明必须可用
./include/OcciWrapper/TypeHandler.h: In static member function ‘static void occiwrapper::TypeHandler<std::basic_string<char, std::char_traits<cator<char> > >::extract(size_t, occiwrapper::AbstractExtractor_)’:
./include/OcciWrapper/TypeHandler.h:393: 错误：‘malloc’在此作用域中尚未声明
./include/OcciWrapper/TypeHandler.h: In static member function ‘static void occiwrapper::TypeHandler<tm>::extract(size_t, occiwrapper::Abstrac
./include/OcciWrapper/TypeHandler.h:450: 错误：‘malloc’在此作用域中尚未声明
./include/OcciWrapper/TypeHandler.h: In static member function ‘static void occiwrapper::TypeHandler<std::vector<T, std::allocator<_CharT> > >onst std::vector<T, std::allocator<_CharT> >&, occiwrapper::AbstractBinder_)’:
./include/OcciWrapper/TypeHandler.h:1262: 错误：‘malloc’的实参不依赖模板参数，所以‘malloc’的声明必须可用
......

**Comment by haih** [comment]
g++ vesion: 4.3.4

**Comment by CUCmehp** [comment]
g++ 4.3的一个兼容性问题，是由于gcc 4.3取消了头文件多层关联造成的。
在TyperHandler中使用了malloc，但未声明<malloc.h>，因此在gcc 4.3编译中出现该问题。
己解决：在TypeHander.h上添加了<malloc.h>头文件引用，下载最近代码即可。
